### ISSUE TITLE
Needs emoji on the description

### ISSUE THREAD

**Issue by paiva** [crocodoyle/npa#1]
The cool kids have it. Please don't close it until you add one.

**Comment by kchatpar** [comment]
I second this @crocodoyle

**Comment by crocodoyle** [comment]
What emoji would you recommend?

**Comment by kchatpar** [comment]
@crocodoyle 
:zap: and :exclamation:

**Comment by crocodoyle** [comment]
Should be fixed, let me know if you still have any issues!
